version: "3"
services:
  proxy:
    container_name: back_proxy
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - /srv/letsencrypt/certs:/etc/nginx/certs:ro
      - /srv/letsencrypt/vhost.d:/etc/nginx/vhost.d
      - /srv/letsencrypt/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    ports:
      - "80:80"
      - "443:443"
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
      
      
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: back_letsencrypt-companion
    restart: always
    volumes:
      - /srv/letsencrypt/certs:/etc/nginx/certs
      - /srv/letsencrypt/vhost.d:/etc/nginx/vhost.d
      - /srv/letsencrypt/html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - proxy
    environment:
      - NGINX_PROXY_CONTAINER=proxy
    logging:
        driver: "json-file"
        options:
            max-size: "50m"
      
  mysite.ru:
    image: nginx
    container_name: mysite.ru
    restart: always
    environment:
#      - HTTPS_METHOD=noredirect
      - HTTPS_METHOD=redirect
      - HSTS=off
      - VIRTUAL_HOST=mysite.ru
      - LETSENCRYPT_HOST=mysite.ru
      - LETSENCRYPT_EMAIL=admin@mysite.ru
#      - CERT_NAME=wc_mysite.ru
    volumes:
      - ./mysite.ru/nginx.conf:/etc/nginx/nginx.conf
    logging:
        driver: "json-file"
        options:
            max-size: "512m"
